### ISSUE TITLE
Compressing mag999_a.dat and decompressing after, outputs a 0 byte file

### ISSUE THREAD

**Issue by bosshunter** [myst6re/qt-lzs#2]
There's a file on battle.fs (FF8) called mag999_a.dat that if you lzs it and then unlzs it, it outputs a .dec file with 0 bytes.

![unknown (2)](https://user-images.githubusercontent.com/3970315/112200513-382c0200-8c07-11eb-9bab-17fd2d5f45c5.png)

**Comment by myst6re** [comment]
Thanks for the report!
Fixed in v1.3
